package com.justjournal.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.Entry;
import com.justjournal.model.Tags;

/**
 * Class _EntryTags was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EntryTags extends CayenneDataObject {

    public static final String ENTRY_LIST_TO_TAG_LIST_PROPERTY = "entryListToTagList";
    public static final String TAGS_TO_ENTRY_PROPERTY = "tagsToEntry";

    public static final String ENTRYID_PK_COLUMN = "entryid";
    public static final String TAGID_PK_COLUMN = "tagid";

    public void setEntryListToTagList(Tags entryListToTagList) {
        setToOneTarget(ENTRY_LIST_TO_TAG_LIST_PROPERTY, entryListToTagList, true);
    }

    public Tags getEntryListToTagList() {
        return (Tags)readProperty(ENTRY_LIST_TO_TAG_LIST_PROPERTY);
    }


    public void addToTagsToEntry(Entry obj) {
        addToManyTarget(TAGS_TO_ENTRY_PROPERTY, obj, true);
    }
    public void removeFromTagsToEntry(Entry obj) {
        removeToManyTarget(TAGS_TO_ENTRY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Entry> getTagsToEntry() {
        return (List<Entry>)readProperty(TAGS_TO_ENTRY_PROPERTY);
    }


}
