package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Favorites was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Favorites extends CayenneDataObject {

    public static final String ENTRYID_PROPERTY = "entryid";
    public static final String OWNER_PROPERTY = "owner";

    public static final String ID_PK_COLUMN = "id";

    public void setEntryid(Long entryid) {
        writeProperty(ENTRYID_PROPERTY, entryid);
    }
    public Long getEntryid() {
        return (Long)readProperty(ENTRYID_PROPERTY);
    }

    public void setOwner(Long owner) {
        writeProperty(OWNER_PROPERTY, owner);
    }
    public Long getOwner() {
        return (Long)readProperty(OWNER_PROPERTY);
    }

}
