package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Hitcount was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Hitcount extends CayenneDataObject {

    public static final String COUNT_PROPERTY = "count";
    public static final String RESOURCE_PROPERTY = "resource";

    public static final String ID_PK_COLUMN = "id";

    public void setCount(Integer count) {
        writeProperty(COUNT_PROPERTY, count);
    }
    public Integer getCount() {
        return (Integer)readProperty(COUNT_PROPERTY);
    }

    public void setResource(String resource) {
        writeProperty(RESOURCE_PROPERTY, resource);
    }
    public String getResource() {
        return (String)readProperty(RESOURCE_PROPERTY);
    }

}
