package com.justjournal.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.Entry;

/**
 * Class _Location was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Location extends CayenneDataObject {

    public static final String TITLE_PROPERTY = "title";
    public static final String LOCATION_TO_ENTRY_PROPERTY = "locationToEntry";

    public static final String ID_PK_COLUMN = "id";

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void addToLocationToEntry(Entry obj) {
        addToManyTarget(LOCATION_TO_ENTRY_PROPERTY, obj, true);
    }
    public void removeFromLocationToEntry(Entry obj) {
        removeToManyTarget(LOCATION_TO_ENTRY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Entry> getLocationToEntry() {
        return (List<Entry>)readProperty(LOCATION_TO_ENTRY_PROPERTY);
    }


}
