package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _MoodThemeData was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MoodThemeData extends CayenneDataObject {

    public static final String HEIGHT_PROPERTY = "height";
    public static final String MOODID_PROPERTY = "moodid";
    public static final String MOODTHEMEID_PROPERTY = "moodthemeid";
    public static final String PICURL_PROPERTY = "picurl";
    public static final String WIDTH_PROPERTY = "width";

    public static final String ID_PK_COLUMN = "id";

    public void setHeight(Byte height) {
        writeProperty(HEIGHT_PROPERTY, height);
    }
    public Byte getHeight() {
        return (Byte)readProperty(HEIGHT_PROPERTY);
    }

    public void setMoodid(Long moodid) {
        writeProperty(MOODID_PROPERTY, moodid);
    }
    public Long getMoodid() {
        return (Long)readProperty(MOODID_PROPERTY);
    }

    public void setMoodthemeid(Long moodthemeid) {
        writeProperty(MOODTHEMEID_PROPERTY, moodthemeid);
    }
    public Long getMoodthemeid() {
        return (Long)readProperty(MOODTHEMEID_PROPERTY);
    }

    public void setPicurl(String picurl) {
        writeProperty(PICURL_PROPERTY, picurl);
    }
    public String getPicurl() {
        return (String)readProperty(PICURL_PROPERTY);
    }

    public void setWidth(Byte width) {
        writeProperty(WIDTH_PROPERTY, width);
    }
    public Byte getWidth() {
        return (Byte)readProperty(WIDTH_PROPERTY);
    }

}
