package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Settings was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Settings extends CayenneDataObject {

    public static final String KEY_NAME_PROPERTY = "keyName";
    public static final String VALUE_PROPERTY = "value";

    public static final String ID_PK_COLUMN = "id";

    public void setKeyName(String keyName) {
        writeProperty(KEY_NAME_PROPERTY, keyName);
    }
    public String getKeyName() {
        return (String)readProperty(KEY_NAME_PROPERTY);
    }

    public void setValue(String value) {
        writeProperty(VALUE_PROPERTY, value);
    }
    public String getValue() {
        return (String)readProperty(VALUE_PROPERTY);
    }

}
