package com.justjournal.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.EntryTags;

/**
 * Class _Tags was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tags extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String TAGS_TO_ENTRY_LIST_PROPERTY = "tagsToEntryList";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToTagsToEntryList(EntryTags obj) {
        addToManyTarget(TAGS_TO_ENTRY_LIST_PROPERTY, obj, true);
    }
    public void removeFromTagsToEntryList(EntryTags obj) {
        removeToManyTarget(TAGS_TO_ENTRY_LIST_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EntryTags> getTagsToEntryList() {
        return (List<EntryTags>)readProperty(TAGS_TO_ENTRY_LIST_PROPERTY);
    }


}
