package com.justjournal.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.User;

/**
 * Class _UserContact was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserContact extends CayenneDataObject {

    public static final String AIM_PROPERTY = "aim";
    public static final String EMAIL_PROPERTY = "email";
    public static final String HP_TITLE_PROPERTY = "hpTitle";
    public static final String HP_URI_PROPERTY = "hpUri";
    public static final String ICQ_PROPERTY = "icq";
    public static final String MSN_PROPERTY = "msn";
    public static final String PHONE_PROPERTY = "phone";
    public static final String YAHOO_PROPERTY = "yahoo";
    public static final String USER_CONTACT_TO_USER_PROPERTY = "userContactToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setAim(String aim) {
        writeProperty(AIM_PROPERTY, aim);
    }
    public String getAim() {
        return (String)readProperty(AIM_PROPERTY);
    }

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setHpTitle(String hpTitle) {
        writeProperty(HP_TITLE_PROPERTY, hpTitle);
    }
    public String getHpTitle() {
        return (String)readProperty(HP_TITLE_PROPERTY);
    }

    public void setHpUri(String hpUri) {
        writeProperty(HP_URI_PROPERTY, hpUri);
    }
    public String getHpUri() {
        return (String)readProperty(HP_URI_PROPERTY);
    }

    public void setIcq(String icq) {
        writeProperty(ICQ_PROPERTY, icq);
    }
    public String getIcq() {
        return (String)readProperty(ICQ_PROPERTY);
    }

    public void setMsn(String msn) {
        writeProperty(MSN_PROPERTY, msn);
    }
    public String getMsn() {
        return (String)readProperty(MSN_PROPERTY);
    }

    public void setPhone(String phone) {
        writeProperty(PHONE_PROPERTY, phone);
    }
    public String getPhone() {
        return (String)readProperty(PHONE_PROPERTY);
    }

    public void setYahoo(String yahoo) {
        writeProperty(YAHOO_PROPERTY, yahoo);
    }
    public String getYahoo() {
        return (String)readProperty(YAHOO_PROPERTY);
    }

    public void addToUserContactToUser(User obj) {
        addToManyTarget(USER_CONTACT_TO_USER_PROPERTY, obj, true);
    }
    public void removeFromUserContactToUser(User obj) {
        removeToManyTarget(USER_CONTACT_TO_USER_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<User> getUserContactToUser() {
        return (List<User>)readProperty(USER_CONTACT_TO_USER_PROPERTY);
    }


}
