package com.justjournal.model.auto;

import com.justjournal.model.User;
import org.apache.cayenne.CayenneDataObject;

/**
 * Class _UserLink was generated by Cayenne. It is probably a good idea to avoid changing this class manually, since it
 * may be overwritten next time code is regenerated. If you need to make any customizations, please use subclass.
 */
public abstract class _UserLink extends CayenneDataObject {

    public static final String TITLE_PROPERTY = "title";
    public static final String URI_PROPERTY = "uri";
    public static final String USER_LINK_TO_USER_PROPERTY = "userLinkToUser";

    public static final String LINKID_PK_COLUMN = "linkid";

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }

    public String getTitle() {
        return (String) readProperty(TITLE_PROPERTY);
    }

    public void setUri(String uri) {
        writeProperty(URI_PROPERTY, uri);
    }

    public String getUri() {
        return (String) readProperty(URI_PROPERTY);
    }

    public void setUserLinkToUser(User userLinkToUser) {
        setToOneTarget(USER_LINK_TO_USER_PROPERTY, userLinkToUser, true);
    }

    public User getUserLinkToUser() {
        return (User) readProperty(USER_LINK_TO_USER_PROPERTY);
    }


}
