package com.justjournal.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.User;

/**
 * Class _UserPic was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserPic extends CayenneDataObject {

    public static final String DATE_MODIFIED_PROPERTY = "dateModified";
    public static final String IMAGE_PROPERTY = "image";
    public static final String MIMETYPE_PROPERTY = "mimetype";
    public static final String USER_PIC_TO_USER_PROPERTY = "userPicToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setDateModified(Date dateModified) {
        writeProperty(DATE_MODIFIED_PROPERTY, dateModified);
    }
    public Date getDateModified() {
        return (Date)readProperty(DATE_MODIFIED_PROPERTY);
    }

    public void setImage(byte[] image) {
        writeProperty(IMAGE_PROPERTY, image);
    }
    public byte[] getImage() {
        return (byte[])readProperty(IMAGE_PROPERTY);
    }

    public void setMimetype(String mimetype) {
        writeProperty(MIMETYPE_PROPERTY, mimetype);
    }
    public String getMimetype() {
        return (String)readProperty(MIMETYPE_PROPERTY);
    }

    public void addToUserPicToUser(User obj) {
        addToManyTarget(USER_PIC_TO_USER_PROPERTY, obj, true);
    }
    public void removeFromUserPicToUser(User obj) {
        removeToManyTarget(USER_PIC_TO_USER_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<User> getUserPicToUser() {
        return (List<User>)readProperty(USER_PIC_TO_USER_PROPERTY);
    }


}
