package com.justjournal.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.User;

/**
 * Class _UserFiles was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserFiles extends CayenneDataObject {

    public static final String DATA_PROPERTY = "data";
    public static final String DATE_MODIFIED_PROPERTY = "dateModified";
    public static final String MIMETYPE_PROPERTY = "mimetype";
    public static final String TITLE_PROPERTY = "title";
    public static final String USER_FILES_TO_USER_PROPERTY = "userFilesToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setData(byte[] data) {
        writeProperty(DATA_PROPERTY, data);
    }
    public byte[] getData() {
        return (byte[])readProperty(DATA_PROPERTY);
    }

    public void setDateModified(Date dateModified) {
        writeProperty(DATE_MODIFIED_PROPERTY, dateModified);
    }
    public Date getDateModified() {
        return (Date)readProperty(DATE_MODIFIED_PROPERTY);
    }

    public void setMimetype(String mimetype) {
        writeProperty(MIMETYPE_PROPERTY, mimetype);
    }
    public String getMimetype() {
        return (String)readProperty(MIMETYPE_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setUserFilesToUser(User userFilesToUser) {
        setToOneTarget(USER_FILES_TO_USER_PROPERTY, userFilesToUser, true);
    }

    public User getUserFilesToUser() {
        return (User)readProperty(USER_FILES_TO_USER_PROPERTY);
    }


}
