package com.justjournal.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.User;

/**
 * Class _UserLink was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserLink extends CayenneDataObject {

    public static final String TITLE_PROPERTY = "title";
    public static final String URI_PROPERTY = "uri";
    public static final String USER_LINK_TO_USER_PROPERTY = "userLinkToUser";

    public static final String LINKID_PK_COLUMN = "linkid";

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setUri(String uri) {
        writeProperty(URI_PROPERTY, uri);
    }
    public String getUri() {
        return (String)readProperty(URI_PROPERTY);
    }

    public void addToUserLinkToUser(User obj) {
        addToManyTarget(USER_LINK_TO_USER_PROPERTY, obj, true);
    }
    public void removeFromUserLinkToUser(User obj) {
        removeToManyTarget(USER_LINK_TO_USER_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<User> getUserLinkToUser() {
        return (List<User>)readProperty(USER_LINK_TO_USER_PROPERTY);
    }


}
