package com.justjournal.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.User;

/**
 * Class _UserStyle was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserStyle extends CayenneDataObject {

    public static final String DOC_PROPERTY = "doc";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String URL_PROPERTY = "url";
    public static final String USER_STYLE_TOUSER_PROPERTY = "userStyleTOUser";

    public static final String ID_PK_COLUMN = "id";

    public void setDoc(String doc) {
        writeProperty(DOC_PROPERTY, doc);
    }
    public String getDoc() {
        return (String)readProperty(DOC_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setUrl(String url) {
        writeProperty(URL_PROPERTY, url);
    }
    public String getUrl() {
        return (String)readProperty(URL_PROPERTY);
    }

    public void addToUserStyleTOUser(User obj) {
        addToManyTarget(USER_STYLE_TOUSER_PROPERTY, obj, true);
    }
    public void removeFromUserStyleTOUser(User obj) {
        removeToManyTarget(USER_STYLE_TOUSER_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<User> getUserStyleTOUser() {
        return (List<User>)readProperty(USER_STYLE_TOUSER_PROPERTY);
    }


}
