<!-- Footer: Begin -->

<div id="footer">
	<p id="copyright">&#169; 2003, 2004, 2005, 2006, 2007, 2008 Lucas Holt.  All rights reserved.</p>
	<p><a href="/privacy.jsp" title="Privacy Policy">Privacy</a> |
        <a href="/sitemap.jsp" title="Site Map">Site Map</a></p>

	<p><a href="http://www.midnightbsd.org/"><img src="/mbsd_button.gif" alt="Powered by MidnightBSD" /></a></p>
</div>

<div style="text-align: center; margin: auto;">
      <script type="text/javascript"><!--
google_ad_client = "pub-1321195614665440";
/* 468x60, created 8/27/08 */
google_ad_slot = "8080888486";
google_ad_width = 468;
google_ad_height = 60;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-560995-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
<!-- Footer: End -->
