<!-- Footer: Begin -->

<div id="footer">
	<p id="copyright">&#169; 2003-2008 Lucas Holt.  All rights reserved.</p>
	<p><a href="/privacy.jsp" title="Privacy Policy">Privacy</a> |
        <a href="/sitemap.jsp" title="Site Map">Site Map</a></p>

	<p><a href="http://www.midnightbsd.org/"><img src="mbsd_button.gif" alt="Powered by MidnightBSD" /></a>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-560995-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
<!-- Footer: End -->
