

            <!-- Header: Begin -->
			
            <div id="header">										
				<img src="/images/jj_header.gif" alt="JustJournal" width="608" height="202" style="border:0;" usemap="#Map" />
				<map name="Map" id="Map"><area shape="rect" coords="483,163,509,196" href="/update.jsp" alt="Write" />
					<area shape="rect" coords="514,163,544,198" href="/search/index.jsp" alt="Search" />
					<area shape="rect" coords="549,165,575,195" href="/support/index.jsp" alt="Help" />
					<area shape="rect" coords="135,93,392,146" href="/index.jsp" alt="JustJournal" />
				</map>
			</div>		         
            <!-- Header: End -->