<!-- Menu: Begin -->
<div id="menu">
	
    <strong>Journal</strong>
    <ul>
    <li>
    <a href="/update.jsp">Update</a>
    </li>
    </ul>
    <strong>Account</strong>
    <ul>
    <li>
    <a href="/login.jsp">Login</a>
    </li>
    <li>
    <a href="/create.jsp">Create</a>
    </li>
    <li>
    <a href="/cancel.jsp">Cancel</a>
    </li>
    </ul>
    <strong>Support</strong>
    <ul>
    <li>
    <a href="/support/">Index</a>
    </li>
    <li>
    <a href="/support/bugs.jsp">Bugs</a>
    </li>
    <li>
    <a href="/users/jjsite">Site Journal</a>
    </li>
    </ul>
    <strong>Open Source</strong>
    <ul>
    <li>
    <a href="opensource/index.h">Status</a>
    </li>
    <li>
    <a href="http://sourceforge.net/projects/justjournal/">SF CVS</a>
    </li>
    </ul>
    <strong>Site</strong>
    <ul>
    <li>
    <a href="/index.h" title="Home">Home</a>
    </li>
    <li>
    <a href="/privacy.jsp" title="Privacy Policy">Privacy</a>
    </li>
    <li>
    <a href="/sitemap.jsp" title="Site Map">Site Map</a>
    </li>
    <li>
    <a href="http://www.cafepress.com/justjournal">JJ Merchandise</a>
    </li>
    </ul>	

</div>
<!-- Menu: End -->