<!-- Footer: Begin -->

<div id="footer">
    <p id="copyright">&#169; 2003 - 2015 Lucas Holt. All rights reserved.</p>

    <p><a href="/#/privacy" title="Privacy Policy">Privacy</a> |
        <a href="/search/index.jsp" title="Search">Search</a>
</div>

<div style="text-align: center; margin: auto;">
    <script type="text/javascript"><!--
        google_ad_client = "pub-1321195614665440";
        /* 468x60, created 8/27/08 */
        google_ad_slot = "8080888486";
        google_ad_width = 468;
        google_ad_height = 60;
        //-->
    </script>
    <script type="text/javascript"
            src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>
</div>

<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-560995-1', 'justjournal.com');
    ga('require', 'linkid', 'linkid.js');
    ga('send', 'pageview');
</script>
<!-- Footer: End -->
