package com.justjournal.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.Entry;
import com.justjournal.model.User;

/**
 * Class _Comments was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Comments extends CayenneDataObject {

    public static final String BODY_PROPERTY = "body";
    public static final String DATE_PROPERTY = "date";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String COMMENT_TO_ENTRY_PROPERTY = "commentToEntry";
    public static final String COMMENT_TO_USER_PROPERTY = "commentToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setBody(String body) {
        writeProperty(BODY_PROPERTY, body);
    }
    public String getBody() {
        return (String)readProperty(BODY_PROPERTY);
    }

    public void setDate(Date date) {
        writeProperty(DATE_PROPERTY, date);
    }
    public Date getDate() {
        return (Date)readProperty(DATE_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setSubject(String subject) {
        writeProperty(SUBJECT_PROPERTY, subject);
    }
    public String getSubject() {
        return (String)readProperty(SUBJECT_PROPERTY);
    }

    public void setCommentToEntry(Entry commentToEntry) {
        setToOneTarget(COMMENT_TO_ENTRY_PROPERTY, commentToEntry, true);
    }

    public Entry getCommentToEntry() {
        return (Entry)readProperty(COMMENT_TO_ENTRY_PROPERTY);
    }


    public void setCommentToUser(User commentToUser) {
        setToOneTarget(COMMENT_TO_USER_PROPERTY, commentToUser, true);
    }

    public User getCommentToUser() {
        return (User)readProperty(COMMENT_TO_USER_PROPERTY);
    }


}
