package com.justjournal.model.auto;

/** Class _Comments was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Comments extends org.apache.cayenne.CayenneDataObject {

    public static final String BODY_PROPERTY = "body";
    public static final String DATE_PROPERTY = "date";
    public static final String EID_PROPERTY = "eid";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String COMMENT_TO_USER_PROPERTY = "commentToUser";
    public static final String COMMENTS_TO_USER_PROPERTY = "CommentsToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setBody(String body) {
        writeProperty("body", body);
    }
    public String getBody() {
        return (String)readProperty("body");
    }
    
    
    public void setDate(java.util.Date date) {
        writeProperty("date", date);
    }
    public java.util.Date getDate() {
        return (java.util.Date)readProperty("date");
    }
    
    
    public void setEid(Long eid) {
        writeProperty("eid", eid);
    }
    public Long getEid() {
        return (Long)readProperty("eid");
    }
    
    
    public void setModified(java.util.Date modified) {
        writeProperty("modified", modified);
    }
    public java.util.Date getModified() {
        return (java.util.Date)readProperty("modified");
    }
    
    
    public void setSubject(String subject) {
        writeProperty("subject", subject);
    }
    public String getSubject() {
        return (String)readProperty("subject");
    }
    
    
    public void setCommentToUser(com.justjournal.model.User commentToUser) {
        setToOneTarget("commentToUser", commentToUser, true);
    }

    public com.justjournal.model.User getCommentToUser() {
        return (com.justjournal.model.User)readProperty("commentToUser");
    } 
    
    
    public void setCommentsToUser(com.justjournal.model.User CommentsToUser) {
        setToOneTarget("CommentsToUser", CommentsToUser, true);
    }

    public com.justjournal.model.User getCommentsToUser() {
        return (com.justjournal.model.User)readProperty("CommentsToUser");
    } 
    
    
}
