package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Content was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Content extends CayenneDataObject {

    public static final String DATA_PROPERTY = "data";
    public static final String DATASIZE_PROPERTY = "datasize";
    public static final String METADATA_PROPERTY = "metadata";
    public static final String MIME_TYPE_PROPERTY = "mimeType";
    public static final String PREFERRED_PROPERTY = "preferred";
    public static final String URI_ID_PROPERTY = "uriId";
    public static final String USERID_PROPERTY = "userid";

    public static final String ID_PK_COLUMN = "id";

    public void setData(byte[] data) {
        writeProperty(DATA_PROPERTY, data);
    }
    public byte[] getData() {
        return (byte[])readProperty(DATA_PROPERTY);
    }

    public void setDatasize(Integer datasize) {
        writeProperty(DATASIZE_PROPERTY, datasize);
    }
    public Integer getDatasize() {
        return (Integer)readProperty(DATASIZE_PROPERTY);
    }

    public void setMetadata(String metadata) {
        writeProperty(METADATA_PROPERTY, metadata);
    }
    public String getMetadata() {
        return (String)readProperty(METADATA_PROPERTY);
    }

    public void setMimeType(String mimeType) {
        writeProperty(MIME_TYPE_PROPERTY, mimeType);
    }
    public String getMimeType() {
        return (String)readProperty(MIME_TYPE_PROPERTY);
    }

    public void setPreferred(String preferred) {
        writeProperty(PREFERRED_PROPERTY, preferred);
    }
    public String getPreferred() {
        return (String)readProperty(PREFERRED_PROPERTY);
    }

    public void setUriId(Long uriId) {
        writeProperty(URI_ID_PROPERTY, uriId);
    }
    public Long getUriId() {
        return (Long)readProperty(URI_ID_PROPERTY);
    }

    public void setUserid(Long userid) {
        writeProperty(USERID_PROPERTY, userid);
    }
    public Long getUserid() {
        return (Long)readProperty(USERID_PROPERTY);
    }

}
