package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Country was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Country extends CayenneDataObject {

    public static final String ISO_PROPERTY = "iso";
    public static final String ISO3_PROPERTY = "iso3";
    public static final String ISO_TITLE_PROPERTY = "isoTitle";
    public static final String NUMCODE_PROPERTY = "numcode";
    public static final String TITLE_PROPERTY = "title";

    public static final String ID_PK_COLUMN = "id";

    public void setIso(String iso) {
        writeProperty(ISO_PROPERTY, iso);
    }
    public String getIso() {
        return (String)readProperty(ISO_PROPERTY);
    }

    public void setIso3(String iso3) {
        writeProperty(ISO3_PROPERTY, iso3);
    }
    public String getIso3() {
        return (String)readProperty(ISO3_PROPERTY);
    }

    public void setIsoTitle(String isoTitle) {
        writeProperty(ISO_TITLE_PROPERTY, isoTitle);
    }
    public String getIsoTitle() {
        return (String)readProperty(ISO_TITLE_PROPERTY);
    }

    public void setNumcode(Short numcode) {
        writeProperty(NUMCODE_PROPERTY, numcode);
    }
    public Short getNumcode() {
        return (Short)readProperty(NUMCODE_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

}
