package com.justjournal.model.auto;

/** Class _EntryTags was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EntryTags extends org.apache.cayenne.CayenneDataObject {


    public static final String ENTRYID_PK_COLUMN = "entryid";
    public static final String TAGID_PK_COLUMN = "tagid";

}
