package com.justjournal.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.Comments;
import com.justjournal.model.EntrySecurity;
import com.justjournal.model.EntryTags;
import com.justjournal.model.Location;
import com.justjournal.model.Mood;
import com.justjournal.model.User;

/**
 * Class _Entry was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Entry extends CayenneDataObject {

    public static final String ALLOW_COMMENTS_PROPERTY = "allowComments";
    public static final String ATTACH_FILE_PROPERTY = "attachFile";
    public static final String ATTACH_IMAGE_PROPERTY = "attachImage";
    public static final String AUTOFORMAT_PROPERTY = "autoformat";
    public static final String BODY_PROPERTY = "body";
    public static final String DATE_PROPERTY = "date";
    public static final String DRAFT_PROPERTY = "draft";
    public static final String EMAIL_COMMENTS_PROPERTY = "emailComments";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String MUSIC_PROPERTY = "music";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String ENTRY_TO_COMMENTS_PROPERTY = "entryToComments";
    public static final String ENTRY_TO_LOCATION_PROPERTY = "entryToLocation";
    public static final String ENTRY_TO_MOOD_PROPERTY = "entryToMood";
    public static final String ENTRY_TO_SECURITY_PROPERTY = "entryToSecurity";
    public static final String ENTRY_TO_TAGS_PROPERTY = "entryToTags";
    public static final String ENTRY_TO_USER_PROPERTY = "entryToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setAllowComments(String allowComments) {
        writeProperty(ALLOW_COMMENTS_PROPERTY, allowComments);
    }
    public String getAllowComments() {
        return (String)readProperty(ALLOW_COMMENTS_PROPERTY);
    }

    public void setAttachFile(Long attachFile) {
        writeProperty(ATTACH_FILE_PROPERTY, attachFile);
    }
    public Long getAttachFile() {
        return (Long)readProperty(ATTACH_FILE_PROPERTY);
    }

    public void setAttachImage(Long attachImage) {
        writeProperty(ATTACH_IMAGE_PROPERTY, attachImage);
    }
    public Long getAttachImage() {
        return (Long)readProperty(ATTACH_IMAGE_PROPERTY);
    }

    public void setAutoformat(String autoformat) {
        writeProperty(AUTOFORMAT_PROPERTY, autoformat);
    }
    public String getAutoformat() {
        return (String)readProperty(AUTOFORMAT_PROPERTY);
    }

    public void setBody(String body) {
        writeProperty(BODY_PROPERTY, body);
    }
    public String getBody() {
        return (String)readProperty(BODY_PROPERTY);
    }

    public void setDate(Date date) {
        writeProperty(DATE_PROPERTY, date);
    }
    public Date getDate() {
        return (Date)readProperty(DATE_PROPERTY);
    }

    public void setDraft(String draft) {
        writeProperty(DRAFT_PROPERTY, draft);
    }
    public String getDraft() {
        return (String)readProperty(DRAFT_PROPERTY);
    }

    public void setEmailComments(String emailComments) {
        writeProperty(EMAIL_COMMENTS_PROPERTY, emailComments);
    }
    public String getEmailComments() {
        return (String)readProperty(EMAIL_COMMENTS_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setMusic(String music) {
        writeProperty(MUSIC_PROPERTY, music);
    }
    public String getMusic() {
        return (String)readProperty(MUSIC_PROPERTY);
    }

    public void setSubject(String subject) {
        writeProperty(SUBJECT_PROPERTY, subject);
    }
    public String getSubject() {
        return (String)readProperty(SUBJECT_PROPERTY);
    }

    public void addToEntryToComments(Comments obj) {
        addToManyTarget(ENTRY_TO_COMMENTS_PROPERTY, obj, true);
    }
    public void removeFromEntryToComments(Comments obj) {
        removeToManyTarget(ENTRY_TO_COMMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Comments> getEntryToComments() {
        return (List<Comments>)readProperty(ENTRY_TO_COMMENTS_PROPERTY);
    }


    public void setEntryToLocation(Location entryToLocation) {
        setToOneTarget(ENTRY_TO_LOCATION_PROPERTY, entryToLocation, true);
    }

    public Location getEntryToLocation() {
        return (Location)readProperty(ENTRY_TO_LOCATION_PROPERTY);
    }


    public void setEntryToMood(Mood entryToMood) {
        setToOneTarget(ENTRY_TO_MOOD_PROPERTY, entryToMood, true);
    }

    public Mood getEntryToMood() {
        return (Mood)readProperty(ENTRY_TO_MOOD_PROPERTY);
    }


    public void setEntryToSecurity(EntrySecurity entryToSecurity) {
        setToOneTarget(ENTRY_TO_SECURITY_PROPERTY, entryToSecurity, true);
    }

    public EntrySecurity getEntryToSecurity() {
        return (EntrySecurity)readProperty(ENTRY_TO_SECURITY_PROPERTY);
    }


    public void addToEntryToTags(EntryTags obj) {
        addToManyTarget(ENTRY_TO_TAGS_PROPERTY, obj, true);
    }
    public void removeFromEntryToTags(EntryTags obj) {
        removeToManyTarget(ENTRY_TO_TAGS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EntryTags> getEntryToTags() {
        return (List<EntryTags>)readProperty(ENTRY_TO_TAGS_PROPERTY);
    }


    public void setEntryToUser(User entryToUser) {
        setToOneTarget(ENTRY_TO_USER_PROPERTY, entryToUser, true);
    }

    public User getEntryToUser() {
        return (User)readProperty(ENTRY_TO_USER_PROPERTY);
    }


}
