package com.justjournal.model.auto;

/** Class _Friends was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Friends extends org.apache.cayenne.CayenneDataObject {

    public static final String FRIENDID_PROPERTY = "friendid";
    public static final String ID_PROPERTY = "id";


    public void setFriendid(Long friendid) {
        writeProperty("friendid", friendid);
    }
    public Long getFriendid() {
        return (Long)readProperty("friendid");
    }
    
    
    public void setId(Long id) {
        writeProperty("id", id);
    }
    public Long getId() {
        return (Long)readProperty("id");
    }
    
    
}
