package com.justjournal.model.auto;

/** Class _FriendsLj was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _FriendsLj extends org.apache.cayenne.CayenneDataObject {

    public static final String COMMUNITY_PROPERTY = "community";

    public static final String ID_PK_COLUMN = "id";
    public static final String USERNAME_PK_COLUMN = "username";

    public void setCommunity(String community) {
        writeProperty("community", community);
    }
    public String getCommunity() {
        return (String)readProperty("community");
    }
    
    
}
