package com.justjournal.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _FriendsLjCache was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FriendsLjCache extends CayenneDataObject {

    public static final String COMMUNITY_PROPERTY = "community";
    public static final String CONTENT_PROPERTY = "content";
    public static final String LASTUPDATED_PROPERTY = "lastupdated";

    public static final String LJUSERNAME_PK_COLUMN = "ljusername";

    public void setCommunity(String community) {
        writeProperty(COMMUNITY_PROPERTY, community);
    }
    public String getCommunity() {
        return (String)readProperty(COMMUNITY_PROPERTY);
    }

    public void setContent(String content) {
        writeProperty(CONTENT_PROPERTY, content);
    }
    public String getContent() {
        return (String)readProperty(CONTENT_PROPERTY);
    }

    public void setLastupdated(Date lastupdated) {
        writeProperty(LASTUPDATED_PROPERTY, lastupdated);
    }
    public Date getLastupdated() {
        return (Date)readProperty(LASTUPDATED_PROPERTY);
    }

}
