package com.justjournal.model.auto;

/** Class _FriendsLjCache was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _FriendsLjCache extends org.apache.cayenne.CayenneDataObject {

    public static final String COMMUNITY_PROPERTY = "community";
    public static final String CONTENT_PROPERTY = "content";
    public static final String LASTUPDATED_PROPERTY = "lastupdated";

    public static final String LJUSERNAME_PK_COLUMN = "ljusername";

    public void setCommunity(String community) {
        writeProperty("community", community);
    }
    public String getCommunity() {
        return (String)readProperty("community");
    }
    
    
    public void setContent(String content) {
        writeProperty("content", content);
    }
    public String getContent() {
        return (String)readProperty("content");
    }
    
    
    public void setLastupdated(java.util.Date lastupdated) {
        writeProperty("lastupdated", lastupdated);
    }
    public java.util.Date getLastupdated() {
        return (java.util.Date)readProperty("lastupdated");
    }
    
    
}
