package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _FriendsLj was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FriendsLj extends CayenneDataObject {

    public static final String COMMUNITY_PROPERTY = "community";

    public static final String ID_PK_COLUMN = "id";
    public static final String USERNAME_PK_COLUMN = "username";

    public void setCommunity(String community) {
        writeProperty(COMMUNITY_PROPERTY, community);
    }
    public String getCommunity() {
        return (String)readProperty(COMMUNITY_PROPERTY);
    }

}
