package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.User;

/**
 * Class _Friends was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Friends extends CayenneDataObject {

    public static final String FRIENDS_TO_FRIEND_USER_PROPERTY = "friendsToFriendUser";
    public static final String FRIENDS_TO_USER_PROPERTY = "friendsToUser";

    public static final String PK_PK_COLUMN = "pk";

    public void setFriendsToFriendUser(User friendsToFriendUser) {
        setToOneTarget(FRIENDS_TO_FRIEND_USER_PROPERTY, friendsToFriendUser, true);
    }

    public User getFriendsToFriendUser() {
        return (User)readProperty(FRIENDS_TO_FRIEND_USER_PROPERTY);
    }


    public void setFriendsToUser(User friendsToUser) {
        setToOneTarget(FRIENDS_TO_USER_PROPERTY, friendsToUser, true);
    }

    public User getFriendsToUser() {
        return (User)readProperty(FRIENDS_TO_USER_PROPERTY);
    }


}
