package com.justjournal.model.auto;

/** Class _Hitcount was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Hitcount extends org.apache.cayenne.CayenneDataObject {

    public static final String COUNT_PROPERTY = "count";

    public static final String RESOURCE_PK_COLUMN = "resource";

    public void setCount(Integer count) {
        writeProperty("count", count);
    }
    public Integer getCount() {
        return (Integer)readProperty("count");
    }
    
    
}
