package com.justjournal.model.auto;

/** Class _MoodThemeData was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _MoodThemeData extends org.apache.cayenne.CayenneDataObject {

    public static final String HEIGHT_PROPERTY = "height";
    public static final String MOODID_PROPERTY = "moodid";
    public static final String MOODTHEMEID_PROPERTY = "moodthemeid";
    public static final String PICURL_PROPERTY = "picurl";
    public static final String WIDTH_PROPERTY = "width";


    public void setHeight(Byte height) {
        writeProperty("height", height);
    }
    public Byte getHeight() {
        return (Byte)readProperty("height");
    }
    
    
    public void setMoodid(Long moodid) {
        writeProperty("moodid", moodid);
    }
    public Long getMoodid() {
        return (Long)readProperty("moodid");
    }
    
    
    public void setMoodthemeid(Long moodthemeid) {
        writeProperty("moodthemeid", moodthemeid);
    }
    public Long getMoodthemeid() {
        return (Long)readProperty("moodthemeid");
    }
    
    
    public void setPicurl(String picurl) {
        writeProperty("picurl", picurl);
    }
    public String getPicurl() {
        return (String)readProperty("picurl");
    }
    
    
    public void setWidth(Byte width) {
        writeProperty("width", width);
    }
    public Byte getWidth() {
        return (Byte)readProperty("width");
    }
    
    
}
