package com.justjournal.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.Entry;

/**
 * Class _Mood was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Mood extends CayenneDataObject {

    public static final String PARENTMOOD_PROPERTY = "parentmood";
    public static final String TITLE_PROPERTY = "title";
    public static final String MOOD_TO_ENTRY_PROPERTY = "moodToEntry";

    public static final String ID_PK_COLUMN = "id";

    public void setParentmood(Byte parentmood) {
        writeProperty(PARENTMOOD_PROPERTY, parentmood);
    }
    public Byte getParentmood() {
        return (Byte)readProperty(PARENTMOOD_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void addToMoodToEntry(Entry obj) {
        addToManyTarget(MOOD_TO_ENTRY_PROPERTY, obj, true);
    }
    public void removeFromMoodToEntry(Entry obj) {
        removeToManyTarget(MOOD_TO_ENTRY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Entry> getMoodToEntry() {
        return (List<Entry>)readProperty(MOOD_TO_ENTRY_PROPERTY);
    }


}
