package com.justjournal.model.auto;

/** Class _MoodThemes was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _MoodThemes extends org.apache.cayenne.CayenneDataObject {

    public static final String DES_PROPERTY = "des";
    public static final String IS_PUBLIC_PROPERTY = "isPublic";
    public static final String NAME_PROPERTY = "name";
    public static final String OWNER_PROPERTY = "owner";

    public static final String ID_PK_COLUMN = "id";

    public void setDes(String des) {
        writeProperty("des", des);
    }
    public String getDes() {
        return (String)readProperty("des");
    }
    
    
    public void setIsPublic(String isPublic) {
        writeProperty("isPublic", isPublic);
    }
    public String getIsPublic() {
        return (String)readProperty("isPublic");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setOwner(Long owner) {
        writeProperty("owner", owner);
    }
    public Long getOwner() {
        return (Long)readProperty("owner");
    }
    
    
}
