package com.justjournal.model.auto;

/** Class _QueueMail was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _QueueMail extends org.apache.cayenne.CayenneDataObject {

    public static final String BODY_PROPERTY = "body";
    public static final String FROM_PROPERTY = "from";
    public static final String PURPOSE_PROPERTY = "purpose";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String TO_PROPERTY = "to";

    public static final String ID_PK_COLUMN = "id";

    public void setBody(String body) {
        writeProperty("body", body);
    }
    public String getBody() {
        return (String)readProperty("body");
    }
    
    
    public void setFrom(String from) {
        writeProperty("from", from);
    }
    public String getFrom() {
        return (String)readProperty("from");
    }
    
    
    public void setPurpose(String purpose) {
        writeProperty("purpose", purpose);
    }
    public String getPurpose() {
        return (String)readProperty("purpose");
    }
    
    
    public void setSubject(String subject) {
        writeProperty("subject", subject);
    }
    public String getSubject() {
        return (String)readProperty("subject");
    }
    
    
    public void setTo(String to) {
        writeProperty("to", to);
    }
    public String getTo() {
        return (String)readProperty("to");
    }
    
    
}
