package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _QueueMail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _QueueMail extends CayenneDataObject {

    public static final String BODY_PROPERTY = "body";
    public static final String FROM_PROPERTY = "from";
    public static final String PURPOSE_PROPERTY = "purpose";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String TO_PROPERTY = "to";

    public static final String ID_PK_COLUMN = "id";

    public void setBody(String body) {
        writeProperty(BODY_PROPERTY, body);
    }
    public String getBody() {
        return (String)readProperty(BODY_PROPERTY);
    }

    public void setFrom(String from) {
        writeProperty(FROM_PROPERTY, from);
    }
    public String getFrom() {
        return (String)readProperty(FROM_PROPERTY);
    }

    public void setPurpose(String purpose) {
        writeProperty(PURPOSE_PROPERTY, purpose);
    }
    public String getPurpose() {
        return (String)readProperty(PURPOSE_PROPERTY);
    }

    public void setSubject(String subject) {
        writeProperty(SUBJECT_PROPERTY, subject);
    }
    public String getSubject() {
        return (String)readProperty(SUBJECT_PROPERTY);
    }

    public void setTo(String to) {
        writeProperty(TO_PROPERTY, to);
    }
    public String getTo() {
        return (String)readProperty(TO_PROPERTY);
    }

}
