package com.justjournal.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Resources was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Resources extends CayenneDataObject {

    public static final String ACTIVE_PROPERTY = "active";
    public static final String NAME_PROPERTY = "name";
    public static final String SECURITY_PROPERTY = "security";

    public static final String ID_PK_COLUMN = "id";

    public void setActive(String active) {
        writeProperty(ACTIVE_PROPERTY, active);
    }
    public String getActive() {
        return (String)readProperty(ACTIVE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setSecurity(Byte security) {
        writeProperty(SECURITY_PROPERTY, security);
    }
    public Byte getSecurity() {
        return (Byte)readProperty(SECURITY_PROPERTY);
    }

}
