package com.justjournal.model.auto;

/** Class _Resources was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Resources extends org.apache.cayenne.CayenneDataObject {

    public static final String ACTIVE_PROPERTY = "active";
    public static final String NAME_PROPERTY = "name";
    public static final String SECURITY_PROPERTY = "security";

    public static final String ID_PK_COLUMN = "id";

    public void setActive(String active) {
        writeProperty("active", active);
    }
    public String getActive() {
        return (String)readProperty("active");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setSecurity(Byte security) {
        writeProperty("security", security);
    }
    public Byte getSecurity() {
        return (Byte)readProperty("security");
    }
    
    
}
