package com.justjournal.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _RssCache was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RssCache extends CayenneDataObject {

    public static final String CONTENT_PROPERTY = "content";
    public static final String INTERVAL_PROPERTY = "interval";
    public static final String LASTUPDATED_PROPERTY = "lastupdated";
    public static final String URI_PROPERTY = "uri";

    public static final String ID_PK_COLUMN = "id";

    public void setContent(String content) {
        writeProperty(CONTENT_PROPERTY, content);
    }
    public String getContent() {
        return (String)readProperty(CONTENT_PROPERTY);
    }

    public void setInterval(Byte interval) {
        writeProperty(INTERVAL_PROPERTY, interval);
    }
    public Byte getInterval() {
        return (Byte)readProperty(INTERVAL_PROPERTY);
    }

    public void setLastupdated(Date lastupdated) {
        writeProperty(LASTUPDATED_PROPERTY, lastupdated);
    }
    public Date getLastupdated() {
        return (Date)readProperty(LASTUPDATED_PROPERTY);
    }

    public void setUri(String uri) {
        writeProperty(URI_PROPERTY, uri);
    }
    public String getUri() {
        return (String)readProperty(URI_PROPERTY);
    }

}
