package com.justjournal.model.auto;

/** Class _RssCache was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _RssCache extends org.apache.cayenne.CayenneDataObject {

    public static final String CONTENT_PROPERTY = "content";
    public static final String INTERVAL_PROPERTY = "interval";
    public static final String LASTUPDATED_PROPERTY = "lastupdated";
    public static final String URI_PROPERTY = "uri";

    public static final String ID_PK_COLUMN = "id";

    public void setContent(String content) {
        writeProperty("content", content);
    }
    public String getContent() {
        return (String)readProperty("content");
    }
    
    
    public void setInterval(Byte interval) {
        writeProperty("interval", interval);
    }
    public Byte getInterval() {
        return (Byte)readProperty("interval");
    }
    
    
    public void setLastupdated(java.util.Date lastupdated) {
        writeProperty("lastupdated", lastupdated);
    }
    public java.util.Date getLastupdated() {
        return (java.util.Date)readProperty("lastupdated");
    }
    
    
    public void setUri(String uri) {
        writeProperty("uri", uri);
    }
    public String getUri() {
        return (String)readProperty("uri");
    }
    
    
}
