package com.justjournal.model.auto;

/** Class _Settings was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Settings extends org.apache.cayenne.CayenneDataObject {

    public static final String VALUE_PROPERTY = "value";

    public static final String NAME_PK_COLUMN = "name";

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }
    
    
}
