package com.justjournal.model.auto;

/** Class _Style was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Style extends org.apache.cayenne.CayenneDataObject {

    public static final String DESC_PROPERTY = "desc";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String TITLE_PROPERTY = "title";

    public static final String ID_PK_COLUMN = "id";

    public void setDesc(String desc) {
        writeProperty("desc", desc);
    }
    public String getDesc() {
        return (String)readProperty("desc");
    }
    
    
    public void setModified(java.util.Date modified) {
        writeProperty("modified", modified);
    }
    public java.util.Date getModified() {
        return (java.util.Date)readProperty("modified");
    }
    
    
    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }
    
    
}
