package com.justjournal.model.auto;

/** Class _Trackback was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Trackback extends org.apache.cayenne.CayenneDataObject {

    public static final String AUTHOR_EMAIL_PROPERTY = "authorEmail";
    public static final String AUTHOR_NAME_PROPERTY = "authorName";
    public static final String BLOGNAME_PROPERTY = "blogname";
    public static final String BODY_PROPERTY = "body";
    public static final String DATE_PROPERTY = "date";
    public static final String EID_PROPERTY = "eid";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String TYPE_PROPERTY = "type";
    public static final String URL_PROPERTY = "url";

    public static final String ID_PK_COLUMN = "id";

    public void setAuthorEmail(String authorEmail) {
        writeProperty("authorEmail", authorEmail);
    }
    public String getAuthorEmail() {
        return (String)readProperty("authorEmail");
    }
    
    
    public void setAuthorName(String authorName) {
        writeProperty("authorName", authorName);
    }
    public String getAuthorName() {
        return (String)readProperty("authorName");
    }
    
    
    public void setBlogname(String blogname) {
        writeProperty("blogname", blogname);
    }
    public String getBlogname() {
        return (String)readProperty("blogname");
    }
    
    
    public void setBody(String body) {
        writeProperty("body", body);
    }
    public String getBody() {
        return (String)readProperty("body");
    }
    
    
    public void setDate(java.util.Date date) {
        writeProperty("date", date);
    }
    public java.util.Date getDate() {
        return (java.util.Date)readProperty("date");
    }
    
    
    public void setEid(Long eid) {
        writeProperty("eid", eid);
    }
    public Long getEid() {
        return (Long)readProperty("eid");
    }
    
    
    public void setModified(java.util.Date modified) {
        writeProperty("modified", modified);
    }
    public java.util.Date getModified() {
        return (java.util.Date)readProperty("modified");
    }
    
    
    public void setSubject(String subject) {
        writeProperty("subject", subject);
    }
    public String getSubject() {
        return (String)readProperty("subject");
    }
    
    
    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }
    
    
    public void setUrl(String url) {
        writeProperty("url", url);
    }
    public String getUrl() {
        return (String)readProperty("url");
    }
    
    
}
