package com.justjournal.model.auto;

import java.util.List;

/** Class _UserStyle was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UserStyle extends org.apache.cayenne.CayenneDataObject {

    public static final String DOC_PROPERTY = "doc";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String URL_PROPERTY = "url";
    public static final String USER_STYLE_TOUSER_PROPERTY = "userStyleTOUser";

    public static final String ID_PK_COLUMN = "id";

    public void setDoc(String doc) {
        writeProperty("doc", doc);
    }
    public String getDoc() {
        return (String)readProperty("doc");
    }
    
    
    public void setModified(java.util.Date modified) {
        writeProperty("modified", modified);
    }
    public java.util.Date getModified() {
        return (java.util.Date)readProperty("modified");
    }
    
    
    public void setUrl(String url) {
        writeProperty("url", url);
    }
    public String getUrl() {
        return (String)readProperty("url");
    }
    
    
    public void addToUserStyleTOUser(com.justjournal.model.User obj) {
        addToManyTarget("userStyleTOUser", obj, true);
    }
    public void removeFromUserStyleTOUser(com.justjournal.model.User obj) {
        removeToManyTarget("userStyleTOUser", obj, true);
    }
    public List getUserStyleTOUser() {
        return (List)readProperty("userStyleTOUser");
    }
    
    
}
