package com.justjournal.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.User;

/**
 * Class _UserLocation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserLocation extends CayenneDataObject {

    public static final String CITY_PROPERTY = "city";
    public static final String COUNTRY_PROPERTY = "country";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String STATE_PROPERTY = "state";
    public static final String ZIP_PROPERTY = "zip";
    public static final String USER_LOCATION_TO_USER_PROPERTY = "userLocationToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setCity(String city) {
        writeProperty(CITY_PROPERTY, city);
    }
    public String getCity() {
        return (String)readProperty(CITY_PROPERTY);
    }

    public void setCountry(Short country) {
        writeProperty(COUNTRY_PROPERTY, country);
    }
    public Short getCountry() {
        return (Short)readProperty(COUNTRY_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setState(Short state) {
        writeProperty(STATE_PROPERTY, state);
    }
    public Short getState() {
        return (Short)readProperty(STATE_PROPERTY);
    }

    public void setZip(String zip) {
        writeProperty(ZIP_PROPERTY, zip);
    }
    public String getZip() {
        return (String)readProperty(ZIP_PROPERTY);
    }

    public void addToUserLocationToUser(User obj) {
        addToManyTarget(USER_LOCATION_TO_USER_PROPERTY, obj, true);
    }
    public void removeFromUserLocationToUser(User obj) {
        removeToManyTarget(USER_LOCATION_TO_USER_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<User> getUserLocationToUser() {
        return (List<User>)readProperty(USER_LOCATION_TO_USER_PROPERTY);
    }


}
