package com.justjournal.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.UserImages;

/**
 * Class _UserImagesAlbumMap was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserImagesAlbumMap extends CayenneDataObject {

    public static final String ALBUM_ID_PROPERTY = "albumId";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String OWNER_PROPERTY = "owner";
    public static final String TO_USER_IMAGES_PROPERTY = "toUserImages";

    public static final String ID_PK_COLUMN = "id";

    public void setAlbumId(Long albumId) {
        writeProperty(ALBUM_ID_PROPERTY, albumId);
    }
    public Long getAlbumId() {
        return (Long)readProperty(ALBUM_ID_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setOwner(Long owner) {
        writeProperty(OWNER_PROPERTY, owner);
    }
    public Long getOwner() {
        return (Long)readProperty(OWNER_PROPERTY);
    }

    public void setToUserImages(UserImages toUserImages) {
        setToOneTarget(TO_USER_IMAGES_PROPERTY, toUserImages, true);
    }

    public UserImages getToUserImages() {
        return (UserImages)readProperty(TO_USER_IMAGES_PROPERTY);
    }


}
