package com.justjournal.model.auto;

import java.util.List;

/** Class _UserPic was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UserPic extends org.apache.cayenne.CayenneDataObject {

    public static final String DATE_MODIFIED_PROPERTY = "dateModified";
    public static final String IMAGE_PROPERTY = "image";
    public static final String MIMETYPE_PROPERTY = "mimetype";
    public static final String USER_PIC_TO_USER_PROPERTY = "userPicToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setDateModified(java.util.Date dateModified) {
        writeProperty("dateModified", dateModified);
    }
    public java.util.Date getDateModified() {
        return (java.util.Date)readProperty("dateModified");
    }
    
    
    public void setImage(byte[] image) {
        writeProperty("image", image);
    }
    public byte[] getImage() {
        return (byte[])readProperty("image");
    }
    
    
    public void setMimetype(String mimetype) {
        writeProperty("mimetype", mimetype);
    }
    public String getMimetype() {
        return (String)readProperty("mimetype");
    }
    
    
    public void addToUserPicToUser(com.justjournal.model.User obj) {
        addToManyTarget("userPicToUser", obj, true);
    }
    public void removeFromUserPicToUser(com.justjournal.model.User obj) {
        removeToManyTarget("userPicToUser", obj, true);
    }
    public List getUserPicToUser() {
        return (List)readProperty("userPicToUser");
    }
    
    
}
