package com.justjournal.model.auto;

import java.util.List;

/** Class _UserLocation was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UserLocation extends org.apache.cayenne.CayenneDataObject {

    public static final String CITY_PROPERTY = "city";
    public static final String COUNTRY_PROPERTY = "country";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String STATE_PROPERTY = "state";
    public static final String ZIP_PROPERTY = "zip";
    public static final String USER_LOCATION_TO_USER_PROPERTY = "userLocationToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }
    
    
    public void setCountry(Short country) {
        writeProperty("country", country);
    }
    public Short getCountry() {
        return (Short)readProperty("country");
    }
    
    
    public void setModified(java.util.Date modified) {
        writeProperty("modified", modified);
    }
    public java.util.Date getModified() {
        return (java.util.Date)readProperty("modified");
    }
    
    
    public void setState(Short state) {
        writeProperty("state", state);
    }
    public Short getState() {
        return (Short)readProperty("state");
    }
    
    
    public void setZip(String zip) {
        writeProperty("zip", zip);
    }
    public String getZip() {
        return (String)readProperty("zip");
    }
    
    
    public void addToUserLocationToUser(com.justjournal.model.User obj) {
        addToManyTarget("userLocationToUser", obj, true);
    }
    public void removeFromUserLocationToUser(com.justjournal.model.User obj) {
        removeToManyTarget("userLocationToUser", obj, true);
    }
    public List getUserLocationToUser() {
        return (List)readProperty("userLocationToUser");
    }
    
    
}
