package com.justjournal.model.auto;

/** Class _UserLink was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UserLink extends org.apache.cayenne.CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String TITLE_PROPERTY = "title";
    public static final String URI_PROPERTY = "uri";

    public static final String LINKID_PK_COLUMN = "linkid";

    public void setId(Long id) {
        writeProperty("id", id);
    }
    public Long getId() {
        return (Long)readProperty("id");
    }
    
    
    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }
    
    
    public void setUri(String uri) {
        writeProperty("uri", uri);
    }
    public String getUri() {
        return (String)readProperty("uri");
    }
    
    
}
