package com.justjournal.model.auto;

import java.util.List;

/** Class _UserLink was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UserLink extends org.apache.cayenne.CayenneDataObject {

    public static final String TITLE_PROPERTY = "title";
    public static final String URI_PROPERTY = "uri";
    public static final String USER_LINK_TO_USER_PROPERTY = "userLinkToUser";

    public static final String LINKID_PK_COLUMN = "linkid";

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }
    
    
    public void setUri(String uri) {
        writeProperty("uri", uri);
    }
    public String getUri() {
        return (String)readProperty("uri");
    }
    
    
    public void addToUserLinkToUser(com.justjournal.model.User obj) {
        addToManyTarget("userLinkToUser", obj, true);
    }
    public void removeFromUserLinkToUser(com.justjournal.model.User obj) {
        removeToManyTarget("userLinkToUser", obj, true);
    }
    public List getUserLinkToUser() {
        return (List)readProperty("userLinkToUser");
    }
    
    
}
