package com.justjournal.model.auto;

import java.util.List;

/** Class _UserImages was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UserImages extends org.apache.cayenne.CayenneDataObject {

    public static final String IMAGE_PROPERTY = "image";
    public static final String MIMETYPE_PROPERTY = "mimetype";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String OWNER_PROPERTY = "owner";
    public static final String TITLE_PROPERTY = "title";
    public static final String USER_IMAGES_ALBUM_MAP_ARRAY_PROPERTY = "userImagesAlbumMapArray";

    public static final String ID_PK_COLUMN = "id";

    public void setImage(byte[] image) {
        writeProperty("image", image);
    }
    public byte[] getImage() {
        return (byte[])readProperty("image");
    }
    
    
    public void setMimetype(String mimetype) {
        writeProperty("mimetype", mimetype);
    }
    public String getMimetype() {
        return (String)readProperty("mimetype");
    }
    
    
    public void setModified(java.util.Date modified) {
        writeProperty("modified", modified);
    }
    public java.util.Date getModified() {
        return (java.util.Date)readProperty("modified");
    }
    
    
    public void setOwner(Long owner) {
        writeProperty("owner", owner);
    }
    public Long getOwner() {
        return (Long)readProperty("owner");
    }
    
    
    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }
    
    
    public void addToUserImagesAlbumMapArray(com.justjournal.model.UserImagesAlbumMap obj) {
        addToManyTarget("userImagesAlbumMapArray", obj, true);
    }
    public void removeFromUserImagesAlbumMapArray(com.justjournal.model.UserImagesAlbumMap obj) {
        removeToManyTarget("userImagesAlbumMapArray", obj, true);
    }
    public List getUserImagesAlbumMapArray() {
        return (List)readProperty("userImagesAlbumMapArray");
    }
    
    
}
