package com.justjournal.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.justjournal.model.User;

/**
 * Class _UserBio was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserBio extends CayenneDataObject {

    public static final String CONTENT_PROPERTY = "content";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String USER_BIO_TO_USER_PROPERTY = "userBioToUser";

    public static final String ID_PK_COLUMN = "id";

    public void setContent(String content) {
        writeProperty(CONTENT_PROPERTY, content);
    }
    public String getContent() {
        return (String)readProperty(CONTENT_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void addToUserBioToUser(User obj) {
        addToManyTarget(USER_BIO_TO_USER_PROPERTY, obj, true);
    }
    public void removeFromUserBioToUser(User obj) {
        removeToManyTarget(USER_BIO_TO_USER_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<User> getUserBioToUser() {
        return (List<User>)readProperty(USER_BIO_TO_USER_PROPERTY);
    }


}
