package com.justjournal.model.auto;

/** Class _UserBio was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UserBio extends org.apache.cayenne.CayenneDataObject {

    public static final String CONTENT_PROPERTY = "content";
    public static final String MODIFIED_PROPERTY = "modified";

    public static final String ID_PK_COLUMN = "id";

    public void setContent(String content) {
        writeProperty("content", content);
    }
    public String getContent() {
        return (String)readProperty("content");
    }
    
    
    public void setModified(java.util.Date modified) {
        writeProperty("modified", modified);
    }
    public java.util.Date getModified() {
        return (java.util.Date)readProperty("modified");
    }
    
    
}
