package com.justjournal.model.auto;

/** Class _UserImagesAlbumMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UserImagesAlbumMap extends org.apache.cayenne.CayenneDataObject {

    public static final String ALBUM_ID_PROPERTY = "albumId";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String OWNER_PROPERTY = "owner";
    public static final String TO_USER_IMAGES_PROPERTY = "toUserImages";


    public void setAlbumId(Long albumId) {
        writeProperty("albumId", albumId);
    }
    public Long getAlbumId() {
        return (Long)readProperty("albumId");
    }
    
    
    public void setModified(java.util.Date modified) {
        writeProperty("modified", modified);
    }
    public java.util.Date getModified() {
        return (java.util.Date)readProperty("modified");
    }
    
    
    public void setOwner(Long owner) {
        writeProperty("owner", owner);
    }
    public Long getOwner() {
        return (Long)readProperty("owner");
    }
    
    
    public void setToUserImages(com.justjournal.model.UserImages toUserImages) {
        setToOneTarget("toUserImages", toUserImages, true);
    }

    public com.justjournal.model.UserImages getToUserImages() {
        return (com.justjournal.model.UserImages)readProperty("toUserImages");
    } 
    
    
}
